### ISSUE TITLE
How do I use my data on the wiki?

### ISSUE THREAD

**Issue by adamk33n3r** [weirdgloop/WikiSync#1]
I've installed this plugin but I can't see how to use it from the wiki's side. If I go to a quest's page it still doesn't show any information. I would assume I would have to write my RSN somewhere like in the RS3 wiki but I don't where.

**Comment by andmcadams** [comment]
We are looking at deploying the required changes to the wiki this week/weekend, but right now we are still testing some stuff on the wiki end so nothing is available publicly yet. We had to release it on plugin-hub first in order to avoid getting blocked on that.

Sometime in the coming week, you should see text inputs similar to RSW's on quest pages where you'll be able to type in your username. I'll leave this issue open until we deploy it on-wiki for everyone to see.

**Comment by andmcadams** [comment]
This should be live now (assuming the cache has had time to purge). So feel free to try it out! Closing this issue now since we have released.
