### ISSUE TITLE
Shield of Arrav Marked as Incomplete

### ISSUE THREAD

**Issue by Ferrariic** [weirdgloop/WikiSync#2]
Issue: Shield of Arrav does not seem to be handled by the plugin - or on the backend - as it does not reflect on the wiki itself.

`Heroes' quest`
![image](https://user-images.githubusercontent.com/5789682/149684668-99dcfa91-8e4b-4bfd-bcd6-cb651e4e7fc9.png)

`Dragon Slayer II`
![image](https://user-images.githubusercontent.com/5789682/149684674-ce73a08f-5d24-4e10-80f8-5f1aaa4b0d57.png)

`In-Game`
![image](https://user-images.githubusercontent.com/5789682/149684722-b17779c2-6efd-4c68-83ec-1f9b63832daa.png)

**Comment by andmcadams** [comment]
Yeah, I think I have an idea of what's going on here. It's definitely server side (I get an "IN_PROGRESS" for SOA from the server), but I'll keep this up to date with progress since there isn't a better place to put issues. FWIW, this is known to happen with miniquests as well, basically anything with special conditions on the varbs. Pretty sure they are all the same issue. Thanks for the report!

**Comment by leejt** [comment]
Shield of Arrav fixed server-side about 10 minutes ago!

**Comment by ChipDenton** [comment]
Still a bug - Sept 2nd 2022
![ShieldOfArrav](https://user-images.githubusercontent.com/50883471/188246327-557587cb-3a5c-4750-a79e-b2312c97c387.jpg)
![ShieldOfArrav2](https://user-images.githubusercontent.com/50883471/188246336-2cf1834f-b832-4c4d-bcad-e5d8d9b9b89e.jpg)
