### ISSUE TITLE
Feature Request: S.T.A.S.H. Unit syncing

### ISSUE THREAD

**Issue by maedas** [weirdgloop/WikiSync#22]
Pretty self explanatory, if possible:
Get stash unit information from the Noticeboard interface (don't know if it's accessible outside of that interface).
Add ability to put in Username on https://oldschool.runescape.wiki/w/STASH page.
Link existing table entries to the data.

**Comment by andmcadams** [comment]
Hey! Similar to the collection log, we don't really want to implement features that won't work for users right away. This is mostly just to keep things easy for users to understand.

Right now you either need to check the stash unit or that interface to know what is filled (AFAIK). If I'm wrong about that or if it gets changed so that there's a way to do this with varbits on login, we could potentially implement it. I'm not exactly sure what we would use it for on the wiki side other than auto-highlighting those stash tables though.
