### ISSUE TITLE
Request: Store Combat Achievements and Standard Achievements

### ISSUE THREAD

**Issue by Ferrariic** [weirdgloop/WikiSync#4]
This information would be useful for those looking to unlock achievements, allowing for automatic filtering of locked and unlocked achievements on the wiki.

This would also be useful from a wiki-perspective to see what achievement are commonly unlocked by players, and the least commonly unlocked achievements.

**Comment by andmcadams** [comment]
I definitely want to do this for combat achievements. That was actually the original motivation for me, but the problem is that we need to come up with a decent UX for users on-wiki before we start gathering this info. It isn't clear what the correct behavior is with current lighttables so in the meantime we opted to focus on leagues.

As far as achievement diaries go, I would have to check the varbs involved. I can't remember if we can easily get the individual tasks or if we can only see some counter varbs. If we can get individual tasks easily then I don't have an issue with this. But similar to combat achievements, I'm not sure what the best UX is on-wiki.

**Comment by andmcadams** [comment]
Similarly to music tracks though, I don't think we would aggregate this data for player stats

**Comment by leejt** [comment]
Combat achievements were added about a week ago to the wiki frontend - see https://oldschool.runescape.wiki/w/Combat_Achievements/Elite for example
